### GET request to example server
GET http://localhost:8080

###
GET http://localhost:8080/api/v1/software-engineer

###
GET http://localhost:8080/events

###
GET http://localhost:8080/events/8


###
POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "",
  "venue": "cam",
  "availableSeats": 10
}

###
DELETE http://localhost:8080/events/8


###
PUT http://localhost:8080/events/8
content-type:application/json

{"id": 3,
  "name": "Tanishq",
  "venue": "Delhi",
  "availableSeats": 200
}