spring.application.name=basics_of_springboot
spring.datasource.url=jdbc:postgresql://localhost:5432/eventdb
spring.datasource.username=postgres
spring.datasource.password=tani
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
